CREATE TABLE [t_item] ( 
[No] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL DEFAULT '0', 
[品名] VARCHAR(200) NOT NULL DEFAULT '', 
[識別コード] VARCHAR(100) NOT NULL DEFAULT '', 
[USD] REAL NOT NULL DEFAULT '0', 
[CNH] REAL NOT NULL DEFAULT '0', 
[USDJPY] REAL NOT NULL DEFAULT '0', 
[CNHJPY] REAL NOT NULL DEFAULT '0', 
[JPY(US)] REAL NOT NULL DEFAULT '0', 
[JPY(CN)] REAL NOT NULL DEFAULT '0', 
[JPY] REAL NOT NULL DEFAULT '0', 
[STATUS] INTEGER NOT NULL DEFAULT '0', 
[作成日] DATETIME, 
[更新日] DATETIME
);
