CREATE TABLE [t_active_index] ( 
[パス] VARCHAR(255) NOT NULL DEFAULT '', 
[モード] VARCHAR(10) NOT NULL DEFAULT '', 
[作成時間(分)] INTEGER NOT NULL DEFAULT '0', 
[対象ファイル数] INTEGER NOT NULL DEFAULT '0', 
[インデックス済み] INTEGER NOT NULL DEFAULT '0', 
[インデックス対象外] INTEGER NOT NULL DEFAULT '0', 
[総バイト数] INTEGER NOT NULL DEFAULT '0', 
[テキスト抽出器] VARCHAR(10) NOT NULL DEFAULT '',
[作成日] DATETIME, 
[更新日] DATETIME,
PRIMARY KEY(パス)
);