//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLSrc {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class m_common_conf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal m_common_conf() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FxCommonLib.SQLSrc.m_common_conf", typeof(m_common_conf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MERGE [dbo].[m_common_conf] AS [DEST] 
        ///USING (SELECT 
        /// @key AS [key]
        ///,@value AS [value]
        ///,@note AS [note]
        ///) AS [SRC] ON ([DEST].[key] = [SRC].[key])
        ///WHEN MATCHED THEN 
        /// UPDATE SET 
        /// [DEST].[key] = [SRC].[key]
        ///,[DEST].[value] = [SRC].[value]
        ///,[DEST].[note] = [SRC].[note]
        ///WHEN NOT MATCHED BY TARGET THEN 
        ///INSERT (
        /// [key]
        ///,[value]
        ///,[note]
        /// ) VALUES (
        /// [SRC].[key]
        ///,[SRC].[value]
        ///,[SRC].[note]
        ///); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MERGE [dbo].[m_common_conf] AS [DEST] 
        ///USING (SELECT 
        /// @key AS [key]
        ///,@value AS [value]
        ///) AS [SRC] ON ([DEST].[key] = [SRC].[key])
        ///WHEN MATCHED THEN 
        /// UPDATE SET 
        /// [DEST].[key] = [SRC].[key]
        ///,[DEST].[value] = [SRC].[value]
        ///WHEN NOT MATCHED BY TARGET THEN 
        ///INSERT (
        /// [key]
        ///,[value]
        ///,[note]
        /// ) VALUES (
        /// [SRC].[key]
        ///,[SRC].[value]
        ///,&apos;&apos;
        ///); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MERGE_KEY_VALUE {
            get {
                return ResourceManager.GetString("MERGE_KEY_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT [key]
        ///      ,[value]
        ///      ,[note]
        ///FROM [dbo].[m_common_conf]
        ///WHERE (1 = 1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_ALL {
            get {
                return ResourceManager.GetString("SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT [key]
        ///      ,[value]
        ///      ,[note]
        ///FROM [dbo].[m_common_conf]
        ///WHERE [key] = @key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_ITEM {
            get {
                return ResourceManager.GetString("SELECT_ITEM", resourceCulture);
            }
        }
    }
}
