//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLSrc {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class t_grid_config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal t_grid_config() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FxCommonLib.SQLSrc.t_grid_config", typeof(t_grid_config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DELETE FROM dbo.[t_grid_config]
        ///WHERE [window_name] = @window_name
        ///AND [grid_name] = @grid_name
        ///AND [login_id] = @login_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE FROM [dbo].[t_grid_config] WHERE [login_id] = @login_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELETE_FROM_T_GRID_CONFIG {
            get {
                return ResourceManager.GetString("DELETE_FROM_T_GRID_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO dbo.[t_grid_config] (
        /// [window_name]
        ///,[grid_name]
        ///,[db_name]
        ///,[login_id]
        ///,[width]
        ///,[height]
        ///,[conf_editable]
        ///,[visible]
        ///,[editable]
        ///,[disp_order]
        ///,[fixed]
        ///,[data_type]
        ///,[max_length]
        ///,[required]
        ///,[primary_key]
        ///,[password_char]
        ///,[note]
        ///,[insert_id]
        ///,[insert_date]
        ///,[update_id]
        ///,[update_date]
        ///) VALUES (
        /// @window_name
        ///,@grid_name
        ///,@db_name
        ///,@login_id
        ///,@width
        ///,@height
        ///,@conf_editable
        ///,@visible
        ///,@editable
        ///,@disp_order
        ///,@col_fixed
        ///,@data_type
        ///,@max_length
        ///,@required
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT 
        /// tgc.[window_name]
        ///,tgc.[grid_name]
        ///,tgc.[db_name]
        ///,tgc.[login_id]
        ///,tgc.[width]
        ///,tgc.[height]
        ///,cnm.[col_name]
        ///,tgc.[conf_editable]
        ///,tgc.[visible]
        ///,tgc.[editable]
        ///,tgc.[disp_order]
        ///,tgc.[fixed] AS [col_fixed]
        ///,tgc.[data_type]
        ///,tgc.[max_length]
        ///,tgc.[required]
        ///,tgc.[primary_key]
        ///,tgc.[password_char]
        ///--,tgc.[note]
        ///,cnm.[note]
        ///,tgc.[insert_id]
        ///,tgc.[insert_date]
        ///,tgc.[update_id]
        ///,tgc.[update_date]
        ///FROM [dbo].[t_grid_config] tgc
        ///LEFT JOIN [dbo].[m_data_dictionary] cnm 
        ///ON (tgc.[ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_ALL {
            get {
                return ResourceManager.GetString("SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT * FROM (
        ///SELECT 
        /// tgc.[window_name]
        ///,tgc.[grid_name]
        ///,tgc.[db_name]
        ///,tgc.[login_id]
        ///,tgc.[width]
        ///,tgc.[height]
        ///,cnm.[col_name]
        ///,tgc.[conf_editable]
        ///,tgc.[visible]
        ///,tgc.[editable]
        ///,tgc.[disp_order]
        ///,tgc.[fixed] AS [col_fixed]
        ///,tgc.[data_type]
        ///,tgc.[max_length]
        ///,tgc.[required]
        ///,tgc.[primary_key]
        ///,tgc.[password_char]
        ///--,tgc.[note]
        ///,cnm.[note]
        ///,tgc.[insert_id]
        ///,tgc.[insert_date]
        ///,tgc.[update_id]
        ///,tgc.[update_date]
        ///FROM [dbo].[t_grid_config] tgc
        ///LEFT JOIN [dbo].[m_data_dictionary [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_CONDITION {
            get {
                return ResourceManager.GetString("SELECT_CONDITION", resourceCulture);
            }
        }
    }
}
