//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLSrc {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class t_window_state {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal t_window_state() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FxCommonLib.SQLSrc.t_window_state", typeof(t_window_state).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DELETE FROM [dbo].[t_window_state]
        ///WHERE [window_name] = @window_name
        ///AND [control_name] = @control_name
        ///AND [login_id] = @login_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE FROM [dbo].[t_window_state] WHERE [login_id] = @login_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELETE_FROM_T_WINDOW_STATE {
            get {
                return ResourceManager.GetString("DELETE_FROM_T_WINDOW_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO [dbo].[t_window_state] (
        /// [window_name]
        ///,[control_name]
        ///,[login_id]
        ///,[conf_value]
        ///,[insert_id]
        ///,[insert_date]
        ///,[update_id]
        ///,[update_date]
        ///) VALUES (
        /// @window_name
        ///,@control_name
        ///,@login_id
        ///,@conf_value
        ///,@login_id
        ///,GETDATE()
        ///,@login_id
        ///,GETDATE()
        ///); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        /// [window_name]
        ///,[control_name]
        ///,[login_id]
        ///,[conf_value]
        ///,[insert_id]
        ///,[insert_date]
        ///,[update_id]
        ///,[update_date]
        ///FROM [dbo].[t_window_state]
        ///WHERE [window_name] = @window_name
        ///AND [login_id] = @login_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_STATE {
            get {
                return ResourceManager.GetString("SELECT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        /// [window_name]
        ///,[control_name]
        ///,[login_id]
        ///,[conf_value]
        ///,[insert_id]
        ///,[insert_date]
        ///,[update_id]
        ///,[update_date]
        ///FROM [dbo].[t_window_state]
        ///WHERE [window_name] = @window_name
        ///AND [control_name] = @control_name
        ///AND [login_id] = @login_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_STATE_ONE {
            get {
                return ResourceManager.GetString("SELECT_STATE_ONE", resourceCulture);
            }
        }
    }
}
